### PR TITLE
support robot_types in DynamicCore. fix #13

### LINKED ISSUE #13: types argument do not work in keyword decorator in DynamicCore
DynamicCore does not support robot_types.
get_keyword_types() should be added.

### PR DESCRIPTION
**Pull request by doyou89**
add get_keyword_types() method

### CODE REVIEW

**Comment by pekkaklarck** [comment]
Thanks for the PR. There are some big missing things, though:

- Support for types specified using Python 3 function annotations. I hope they can be passed to RF as-is and let it handle all strange corner cases there are.
- Tests.
- Type support to the included `@keyword` decorator when using RF < 3.1.

**Comment by pekkaklarck** [comment]
Let me know do you want to continue working with this. I plan to concentrate on PythonLibCore in the somewhat near future, but I have some other projects I need to look at first.

**Comment by doyou89** [comment]
Not now, but if I have time, I will add test cases. However, there is no idea for the method of supporting python3 function annotation and RF 3.1 or less.

**Comment by doyou89** [comment]
utest added for get_keyword_types().
For atest, I have no idea how to test the keywords defined in RobotTypes class for only DynamicCore case.

**Comment by pekkaklarck** [comment]
No type info helps with RF < 3.1. Annotations are the easiest way to specify types and should definitely be supported by PythonLibCore. The support to specify type info using `@keyword` decorator exists mainly to support Python 2.

I don't have time to look at acceptance tests (or this PR) more closely at the momment. I try to reserve time for this project once we get RF 3.2 alpha 1 out.

**Comment by aaltat** [comment]
Closing due #22

**Pull request closed without merging**
